name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free up Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install mercurial \
          python3 python3-dev python3-venv \
          curl \
          jq \
          ccache

      - name: Build
        run: bash build.sh

      - name: Get Firefox version
        id: version
        run: |
          VERSION=$(curl -s https://product-details.mozilla.org/1.0/firefox_versions.json | jq -r '.LATEST_FIREFOX_VERSION')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set Release Tag Output
        id: release-tag
        run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./mozilla-unified/objdir-opt/dist/*.tar.*"
          tag: linux-v${{ steps.release-tag.outputs.version }}-${{ steps.release-tag.outputs.NOW }}
